/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Practice Next */
        get: operations["practice_next_api_practice_next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/replenish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replenish */
        post: operations["replenish_api_practice_replenish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Problem */
        get: operations["get_problem_api_problems__problem_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Problem
         * @description Atomically stamps `served_at` on first call (amendment 41) — a single `UPDATE ...
         *     RETURNING` is its own atomic unit, idempotent on repeat calls.
         */
        post: operations["open_problem_api_problems__problem_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Code */
        post: operations["run_code_api_problems__problem_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Code */
        post: operations["submit_code_api_problems__problem_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/give-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Give Up */
        post: operations["give_up_api_problems__problem_id__give_up_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/problems/{problem_id}/hints/{rung}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal Hint */
        post: operations["reveal_hint_api_problems__problem_id__hints__rung__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress */
        get: operations["progress_api_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CodeRequest */
        CodeRequest: {
            /** Code */
            code: string;
        };
        /** Complexity */
        Complexity: {
            /** Time */
            time: string;
            /** Space */
            space: string;
        };
        /**
         * FailingCaseView
         * @description §8.3/§9: the first failing private case's input, expected output, and the user's output.
         */
        FailingCaseView: {
            /** Input */
            input: unknown[];
            /** Expected */
            expected: unknown;
            /** Actual */
            actual: unknown;
        };
        /**
         * GenerationFailureCode
         * @enum {string}
         */
        GenerationFailureCode: "provider_unavailable" | "generation_invalid" | "quality_mismatch" | "verification_failed" | "verification_unavailable" | "deadline_exceeded";
        /**
         * GenerationJobStatus
         * @description Mirrors the DB `job_status` enum (migration 0001, PLAN_BACKEND.md §4).
         * @enum {string}
         */
        GenerationJobStatus: "queued" | "planning" | "building" | "verifying" | "ready" | "failed";
        /**
         * GenerationPhase
         * @enum {string}
         */
        GenerationPhase: "waiting" | "selecting" | "drafting" | "independent_review" | "checking_examples" | "stress_testing" | "repairing" | "finalizing" | "ready" | "failed";
        /**
         * GenerationRecoveryReason
         * @enum {string}
         */
        GenerationRecoveryReason: "format" | "activity_fit" | "test_disagreement" | "provider" | "verification_infrastructure";
        /** GiveUpResponse */
        GiveUpResponse: {
            /** Reference Solution */
            reference_solution: string;
            rating_update: components["schemas"]["RatingUpdateView"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HintResponse */
        HintResponse: {
            /** Rung */
            rung: number;
            /** Text */
            text: string;
        };
        /** JobStub */
        JobStub: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["GenerationJobStatus"];
            phase: components["schemas"]["GenerationPhase"];
            /**
             * Repair Count
             * @default 0
             */
            repair_count: number;
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
            /**
             * Max Attempts
             * @default 2
             */
            max_attempts: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Phase Started At
             * Format: date-time
             */
            phase_started_at: string;
            recovery_reason?: components["schemas"]["GenerationRecoveryReason"] | null;
            failure_code?: components["schemas"]["GenerationFailureCode"] | null;
        };
        /** MeResponse */
        MeResponse: {
            /** Types */
            types: components["schemas"]["TypeProfileView"][];
        };
        /**
         * PracticeNextResponse
         * @description `GET /api/practice/next` (amendments 36, 41): a pure-read stub, never the statement.
         */
        PracticeNextResponse: {
            /**
             * State
             * @enum {string}
             */
            state: "active" | "generating" | "generation_failed" | "stalled";
            /** Problem Id */
            problem_id?: string | null;
            /**
             * Opened
             * @default false
             */
            opened: boolean;
            job?: components["schemas"]["JobStub"] | null;
        };
        /**
         * ProblemView
         * @description Unresolved view (§9): private tests, unrevealed hints, and both solutions are not fields
         *     of this model, so they cannot leak by construction — not because a route remembers to
         *     scrub them. Siblings with `ResolvedProblemView`, not a superclass, so the two can never be
         *     confused by response-model coercion.
         */
        ProblemView: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Primary Type */
            primary_type: string;
            /** Support Types */
            support_types: string[];
            /** Shape */
            shape: string;
            /** Problem Rating */
            problem_rating: number;
            /** Is Probe */
            is_probe: boolean;
            /** Title */
            title: string;
            /** Statement Md */
            statement_md: string;
            /** Constraints */
            constraints: string[];
            signature: components["schemas"]["Signature"];
            /** Starter Code */
            starter_code: string;
            /** Public Tests */
            public_tests: components["schemas"]["TestCaseView"][];
            complexity: components["schemas"]["Complexity"];
            /** Par Minutes */
            par_minutes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Served At */
            served_at: string | null;
            /** Revealed Hints */
            revealed_hints: string[];
        };
        /** ProgressResponse */
        ProgressResponse: {
            /** Rating History */
            rating_history: components["schemas"]["RatingHistoryPoint"][];
            /** Recent Problems */
            recent_problems: components["schemas"]["ResolvedProblemSummary"][];
        };
        /** RatingHistoryPoint */
        RatingHistoryPoint: {
            /** Type Slug */
            type_slug: string;
            /** Rating Before */
            rating_before: number;
            /** Rating After */
            rating_after: number;
            /** Delta */
            delta: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RatingUpdateView
         * @description §9, #22: every resolution response carries a full rating-update breakdown.
         */
        RatingUpdateView: {
            /** Type Slug */
            type_slug: string;
            /** Rating Before */
            rating_before: number;
            /** Rating After */
            rating_after: number;
            /** Delta */
            delta: number;
            /** Problem Rating */
            problem_rating: number;
            /** Expected Score */
            expected_score: number;
            /** Performance Score */
            performance_score: number;
            /** K Factor */
            k_factor: number;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        };
        /** ReplenishResponse */
        ReplenishResponse: {
            /** Created */
            created: string[];
        };
        /** ResolvedProblemSummary */
        ResolvedProblemSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Primary Type */
            primary_type: string;
            /** Status */
            status: string;
            /** Resolved At */
            resolved_at: string | null;
            /** Problem Rating */
            problem_rating: number;
        };
        /**
         * ResolvedProblemView
         * @description Produced only once status is `solved`/`given_up` (§9): adds the reference solution, the
         *     full hint ladder, and the private tests for post-mortem study.
         */
        ResolvedProblemView: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Primary Type */
            primary_type: string;
            /** Support Types */
            support_types: string[];
            /** Shape */
            shape: string;
            /** Problem Rating */
            problem_rating: number;
            /** Is Probe */
            is_probe: boolean;
            /** Title */
            title: string;
            /** Statement Md */
            statement_md: string;
            /** Constraints */
            constraints: string[];
            signature: components["schemas"]["Signature"];
            /** Starter Code */
            starter_code: string;
            /** Public Tests */
            public_tests: components["schemas"]["TestCaseView"][];
            complexity: components["schemas"]["Complexity"];
            /** Par Minutes */
            par_minutes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Served At */
            served_at: string | null;
            /** Hints */
            hints: string[];
            /** Private Tests */
            private_tests: components["schemas"]["TestCaseView"][];
            /** Reference Solution */
            reference_solution: string;
            /** Resolved At */
            resolved_at: string | null;
        };
        /** RunResponse */
        RunResponse: {
            /** Results */
            results: components["schemas"]["TestOutcome"][];
            /** Passed */
            passed: boolean;
        };
        /**
         * Signature
         * @description A generated problem's callable shape: what the judge calls and what the frontend renders
         *     as starter code (§8.4). `order_insensitive` applies to the *return* value only — a list
         *     return compared as a multiset (e.g. "any valid ordering").
         */
        Signature: {
            /** Func Name */
            func_name: string;
            /** Params */
            params: components["schemas"]["SignatureParam"][];
            returns: components["schemas"]["ValueType"];
            /**
             * Order Insensitive
             * @default false
             */
            order_insensitive: boolean;
        };
        /** SignatureParam */
        SignatureParam: {
            /** Name */
            name: string;
            type: components["schemas"]["ValueType"];
        };
        /**
         * SubmitResponse
         * @description §8.3: a public failure demotes `kind` to `'run'`; an all-private-pass submit sets
         *     `solved=True` and carries `rating_update`.
         */
        SubmitResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "run" | "submit";
            /** Passed */
            passed: boolean;
            /**
             * Solved
             * @default false
             */
            solved: boolean;
            /** Results */
            results: components["schemas"]["TestOutcome"][];
            failing_case?: components["schemas"]["FailingCaseView"] | null;
            rating_update?: components["schemas"]["RatingUpdateView"] | null;
        };
        /**
         * TestCaseView
         * @description A test case as shown to the client: args + the agreed expected value, no `value_type`
         *     (the client doesn't need the comparator's internals).
         */
        TestCaseView: {
            /** Args */
            args: unknown[];
            /** Expected */
            expected: unknown;
        };
        /** TestOutcome */
        TestOutcome: {
            /** Index */
            index: number;
            verdict: components["schemas"]["Verdict"];
            /** Value */
            value?: unknown;
            /** Error */
            error?: string | null;
            /**
             * Printed
             * @default
             */
            printed: string;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
        };
        /**
         * TypeProfileView
         * @description One row of `GET /api/me` (§9): a type's learner-model state.
         */
        TypeProfileView: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Rating */
            rating: number;
            /** Attempts */
            attempts: number;
            /** Evidenced */
            evidenced: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValueType
         * @description `T ::= int | float | bool | str | T? | T[]`.
         *
         *     `list_depth` counts the `[]` nesting (0 = scalar); `nullable` marks the *leaf* scalar as
         *     `T?` — e.g. a level-order binary tree is `ValueType(kind="int", nullable=True, list_depth=1)`.
         */
        ValueType: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "int" | "float" | "bool" | "str";
            /**
             * Nullable
             * @default false
             */
            nullable: boolean;
            /**
             * List Depth
             * @default 0
             */
            list_depth: number;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "pass" | "wrong_answer" | "error" | "timeout";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean | string;
                    };
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    practice_next_api_practice_next_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeNextResponse"];
                };
            };
        };
    };
    replenish_api_practice_replenish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplenishResponse"];
                };
            };
        };
    };
    get_problem_api_problems__problem_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemView"] | components["schemas"]["ResolvedProblemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_problem_api_problems__problem_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemView"] | components["schemas"]["ResolvedProblemView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_code_api_problems__problem_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_code_api_problems__problem_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    give_up_api_problems__problem_id__give_up_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GiveUpResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_hint_api_problems__problem_id__hints__rung__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
                rung: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HintResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_api_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResponse"];
                };
            };
        };
    };
}
