// Seeds/tears down the single approved problem the load test submits against. Every row this
// creates is tagged with `runId` (via `internal_name`) so cleanup can find exactly what it made —
// docs/CONTRACTS.md §13 rule 3: prefer creating and cleaning up only your own rows over truncating
// shared tables. This never touches a row it didn't create itself.
import { insertProblemConcepts, insertProblemVersion, query, withTransaction } from "@leetmind/db";
import { newId, type ProblemVersion } from "@leetmind/shared";
import { HIDDEN_TESTS, SIGNATURE } from "./sources.js";

// Matches the taxonomy seed (docs/CONTRACTS.md §3) — arrays_hashing is the root concept and
// always present, so the FK on problem_concepts is satisfiable without inventing new rows.
const CONCEPT_ID = "arrays_hashing";

export interface SeededLoadtestProblem {
  problemId: string;
  versionId: string;
  runId: string;
}

export async function seedLoadtestProblem(runId: string): Promise<SeededLoadtestProblem> {
  const problemId = newId();
  const versionId = newId();
  const internalName = `loadtest-arith-${runId}`;

  const content: ProblemVersion = {
    problem_id: problemId,
    version: 1,
    title: "Load Test: Sum Two Integers",
    internal_name: internalName,
    statement_md:
      "Return the sum of two integers `a` and `b`. (Synthetic problem generated by scripts/loadtest for M5 load testing — not part of the real content pool.)",
    constraints_md: "-1000000 <= a, b <= 1000000",
    signature: SIGNATURE,
    examples: [{ args: [1, 2], expected: 3, explanation: "1 + 2 = 3" }],
    concepts: [{ id: CONCEPT_ID, role: "primary", weight: 1 }],
    difficulty: { rating: 1200, confidence: "generated" },
    expected_active_minutes: [1, 3],
    target_complexity: { time: "O(1)", space: "O(1)" },
    reference_solution_py: "def solve(a, b):\n    return a + b\n",
    brute_force_py: "def solve(a, b):\n    return a + b\n",
    input_generator_py: "",
    comparator: "exact",
    hidden_tests: HIDDEN_TESTS.map((t) => ({
      args: t.args,
      expected: t.expected,
      origin: "random" as const,
    })),
    mutants_py: [],
    hints: {
      l1_orientation: "Think about what operation combines two numbers.",
      l2_conceptual: "Consider the arithmetic operator that combines two quantities.",
      l3_structural: "Return a plus b directly.",
      outline: "return a + b",
      editorial_md: "# Editorial\nAdd the two numbers and return the result.",
    },
    provenance: {
      mode: "novel",
      model: "loadtest-fixture",
      prompt_version: "v1",
      generated_at: new Date().toISOString(),
    },
    state: "approved",
  };

  await query("insert into problems (id, internal_name) values ($1, $2)", [
    problemId,
    internalName,
  ]);
  await withTransaction((client) =>
    insertProblemVersion(client, {
      id: versionId,
      problem_id: problemId,
      version: 1,
      state: "approved",
      content: content as unknown as Record<string, unknown>,
      title: content.title,
      difficulty_rating: content.difficulty.rating,
      difficulty_confidence: "generated",
      expected_min_minutes: content.expected_active_minutes[0],
      expected_max_minutes: content.expected_active_minutes[1],
      comparator: content.comparator,
      provenance: content.provenance,
    }),
  );
  await withTransaction((client) =>
    insertProblemConcepts(client, versionId, [{ id: CONCEPT_ID, role: "primary", weight: 1 }]),
  );

  return { problemId, versionId, runId };
}

/** Deletes everything this run's seeded problem produced: submissions, execution attempts,
 * learning events, hint events, then the problem/version/concepts rows themselves. Scoped
 * entirely by `versionId`/`problemId` this run created — never a table-wide truncate. */
export async function cleanupLoadtestProblem(
  seeded: SeededLoadtestProblem,
): Promise<{ deletedSubmissions: number }> {
  const submissionIds = await query<{ id: string }>(
    "select id from submissions where problem_version_id = $1",
    [seeded.versionId],
  );
  const ids = submissionIds.map((r) => r.id);
  if (ids.length > 0) {
    await query("delete from learning_events where submission_id = any($1)", [ids]);
    await query("delete from execution_attempts where submission_id = any($1)", [ids]);
  }
  await query("delete from learning_events where problem_version_id = $1", [seeded.versionId]);
  await query("delete from hint_events where problem_version_id = $1", [seeded.versionId]);
  await query("delete from submissions where problem_version_id = $1", [seeded.versionId]);
  await query("delete from problem_concepts where problem_version_id = $1", [seeded.versionId]);
  await query("delete from problem_versions where id = $1", [seeded.versionId]);
  await query("delete from problems where id = $1", [seeded.problemId]);
  return { deletedSubmissions: ids.length };
}
